trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Install_Node
  displayName: 'Install Node.js'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x' # Ensure this version is available
      displayName: 'Install Node.js'

- job: Client_Build_And_Run
  displayName: 'Build Client (Next.js) and Prepare for CD'
  dependsOn: Install_Node
  steps:
    - script: |
        cd client
        npm install # Ensure package.json exists and dependencies are correct
        npm run build # Ensure build script is defined in package.json
      displayName: 'Install and Build Client'

- job: Server_Run_And_CD
  displayName: 'Run Server (Node.js) and Prepare for CD'
  dependsOn: Install_Node
  steps:
    - script: |
        cd server
        npm install # Ensure package.json exists and dependencies are correct
      displayName: 'Install Server Dependencies'

- job: copy_publish_artifacts
  displayName: 'Copy and Publish Artifacts'
  dependsOn: 
    - Client_Build_And_Run
    - Server_Run_And_CD
  steps:
    - task: CopyFiles@2
      inputs:
        Contents: |
          client/**
          server/**
        TargetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copy Artifacts to Final Directory'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'release'
        publishLocation: 'Container'
      displayName: 'Publish Final Artifacts'
